Handle failure in from_index
chris-zen/coremidi pull request #6
Opened 2017-07-14 17:07 UTC by Boddlnagg

Fixes #4.

2017-07-16 18:49 UTC, chris-zen requested changes
@Boddlnagg Good catch !
I requested a couple of small changes to use pattern matching, just a personal preference to make the code more readable.
Thank you very much for the contribution !

2017-07-16 18:49 UTC, chris-zen commented on src/endpoints/destinations.rs
> +        }
Would you mind using pattern matching ?

```rust
match endpoint_ref {
  0 => None,
  _ => Some(Destination { endpoint: Endpoint { object: Object(endpoint_ref) } })
}
```

2017-07-16 18:49 UTC, chris-zen commented on src/endpoints/sources.rs
> +        }
Same here.

2017-07-16 18:51 UTC, chris-zen commented
@Boddlnagg By the way I just saw that there are tests failing because `from_index` changed to an Option.

2017-07-17 10:36 UTC, Boddlnagg commented
I pushed a new version which uses `match` and passes `cargo test`.

2017-09-03 09:52 UTC, chris-zen approved these changes
Great, thanks.

2017-09-03 09:52 UTC, merged